version: "3.9"

services:
  db:
    image: "postgres:14-alpine"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgresnet
    env_file: ./config/.env

  web:
    image: "{{ cookiecutter.project_name }}:dev"
    build:
      target: development_build
      context: .
      dockerfile: ./docker/django/Dockerfile
      args:
        DJANGO_ENV: development
      cache_from:
        - "{{ cookiecutter.project_name }}:dev"
        - "{{ cookiecutter.project_name }}:latest"
        - "*"
    volumes:
      - django-static:/var/www/django/static
    depends_on:
      - db
    networks:
      - webnet
      - postgresnet
    env_file: ./config/.env
    environment:
      DJANGO_DATABASE_HOST: db
    command: python -Wd manage.py runserver 0.0.0.0:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/?format=json"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  postgresnet:
  webnet:

volumes:
  pgdata:
  django-static:
